name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Update Dependencies
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        
    - name: Update dependencies
      run: |
        # Update requirements if they exist
        if [ -f requirements.in ]; then
          pip-compile --upgrade requirements.in
        fi
        
        if [ -f requirements-dev.in ]; then
          pip-compile --upgrade requirements-dev.in
        fi
        
        # If no .in files, create them from existing requirements
        if [ -f requirements.txt ] && [ ! -f requirements.in ]; then
          cp requirements.txt requirements.in
          pip-compile --upgrade requirements.in
        fi
        
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "No dependency updates needed"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Dependencies have been updated"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Pull Request
      if: steps.changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates generated by the dependency update workflow.
          
          ### Changes
          - Updated Python dependencies to their latest compatible versions
          
          ### Review Checklist
          - [ ] All tests pass
          - [ ] No breaking changes introduced
          - [ ] Security vulnerabilities addressed
          
          This PR was automatically generated by the dependency update workflow.
        branch: automated/dependency-updates
        delete-branch: true

  security-audit:
    runs-on: ubuntu-latest
    name: Security Audit
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install safety pip-audit
        
    - name: Run security audit
      run: |
        # Check with safety
        if [ -f requirements.txt ]; then
          safety check -r requirements.txt --json > safety-report.json || true
        fi
        
        # Check with pip-audit
        if [ -f requirements.txt ]; then
          pip-audit -r requirements.txt --format=json --output=audit-report.json || true
        fi
        
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          audit-report.json